## Awards

Awarded Associate Fellowship - [Stirling Framework Evidencing Learning and Teaching Enhancement (SFELTE)](https://www.stir.ac.uk/about/professional-services/information-services-and-library/current-students-and-staff/academic-development/accredited-cpd/sfelte-experience-route/), October 2022. 

## Supervisor 

Supervised quantitative and qualitative undergraduate Sociology, Social Policy and Criminology dissertations. Supervised topics include perceptions towards LGBTQIA+ issues and 'rainbow washing', migration, and social inequalities. 

## Lecturer 

Lectured on a few undergraduate and postgraduate modules in Faculty of Social Sciences at the University of Stirling. This includes a lecture on New Scots Refugee Policy for undergraduate module on Race, Ethnicity and Migration. I've also provided sessions to PGRs on how to write a master's thesis, navigating the student-supervisor relationship, and doing a PhD with quantitative elements. Scot has also lectured to students at Yerevan State University, Armenia on using big data in social science research. 

## Teaching assistant 

During my PhD at the University of Stirling, I have regularly taught on modules about the research process and quantitative methods which involve both seminar and practical labs in SPSS and Stata. I have also got experience as teaching assistant on modules centered around sociological concepts and theories. I regularly mark assignments and provide feedback to undergraduate students on a range of sociology and criminology modules. 

Lab and seminar tutor:

Quantitative Data Analysis (ASRP004; SCQF level 11).

Research Design and Process (ASRP002; SCQF level 11). 

Research Process II (SPCU9C6; SCQF level. 10).

Social Divisions (SPCU912; SCQF level. 7). 

Marking and assessment: 

Crime and Criminal Justice (SCQF9T4; level 9).

Understanding Social Policy (SPCU913; SCQF level 9).

Development of Social Theory (SPCU9C4; SCQF level 9).

Social Differentiation (SPCU911; SCQF level 7). 






